name: Build Test

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main, master ]

env:
  NODE_VERSION: '18'

jobs:
  test-build:
    name: Test Build
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Setup platform-specific tools
        run: |
          # Install platform-specific dependencies
          if [ "$RUNNER_OS" = "macOS" ]; then
            echo "Setting up macOS..."
            # macOS should have curl by default
          elif [ "$RUNNER_OS" = "Linux" ]; then
            echo "Setting up Linux..."
            sudo apt-get update
            sudo apt-get install -y unzip curl
          elif [ "$RUNNER_OS" = "Windows" ]; then
            echo "Setting up Windows..."
            # Windows should have PowerShell by default
          fi
          
      - name: Download external dependencies
        run: |
          echo "Platform: $RUNNER_OS"
          echo "Node version: $(node --version)"
          echo "Current directory: $(pwd)"
          echo "Contents of scripts/:"
          ls -la scripts/
          echo "Attempting to download dependencies..."
          node scripts/download-deps.js
        
      - name: Build application
        run: npm run build
        
      - name: Verify build output
        run: |
          # Check that main files exist
          if [ ! -f "out/main.js" ]; then
            echo "❌ main.js not found"
            exit 1
          fi
          if [ ! -f "out/preload.cjs" ]; then
            echo "❌ preload.cjs not found"
            exit 1
          fi
          if [ ! -d "dist/renderer" ]; then
            echo "❌ renderer directory not found"
            exit 1
          fi
          echo "✅ Build verification passed"
          
      - name: Check external dependencies
        run: |
          # Verify that external dependencies were downloaded
          if [ ! -f "bin/ffmpeg" ] && [ ! -f "bin/ffmpeg.exe" ]; then
            echo "❌ ffmpeg not found"
            exit 1
          fi
          if [ ! -f "bin/ffprobe" ] && [ ! -f "bin/ffprobe.exe" ]; then
            echo "❌ ffprobe not found"
            exit 1
          fi
          if [ ! -f "bin/yt-dlp" ] && [ ! -f "bin/yt-dlp.exe" ]; then
            echo "❌ yt-dlp not found"
            exit 1
          fi
          echo "✅ External dependencies verified"
          
      - name: Run type check
        run: npm run typecheck
