name: Build and Release

on:
  push:
    tags:
      - 'v*'   # v-prefixed tags like v1.0.0
      - '*'    # any tag, e.g. 0.26
  create:
    tags:
      - 'v*'   # v-prefixed tags
      - '*'    # any tag
  workflow_dispatch: {}

# Required so the workflow can create GitHub Releases
permissions:
  contents: write

env:
  NODE_VERSION: '20'

jobs:
  build-windows:
    name: Build for Windows
    runs-on: windows-latest
    env:
      APP_VERSION: ${{ github.ref_name }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          
      - name: Install dependencies
        shell: pwsh
        run: |
          Write-Host "Attempting to install dependencies with npm ci..."
          npm ci
          if ($LASTEXITCODE -ne 0) {
            Write-Host "npm ci failed, trying npm install instead..."
            npm install
            if ($LASTEXITCODE -ne 0) {
              throw "npm install failed"
            }
          }
        
      - name: Download external dependencies
        run: node scripts/download-deps.js
        
      - name: Build application
        run: npm run build
        
      - name: Package application
        run: npx tsx scripts/build-electron.ts
        
      - name: Create Windows archive
        shell: pwsh
        run: |
          # Zip the packaged app folder using the tag version
          $folder = Get-ChildItem -Path "dist" -Directory -Name | Where-Object { $_ -like "video-trimmer-*-win32-*" } | Select-Object -First 1
          if (-not $folder) { throw "Packaged folder not found under dist" }
          $src = Join-Path "dist" $folder
          $version = $env:APP_VERSION
          if (-not $version) { $version = "unknown" }
          $dst = "dist\video-trimmer-$version-windows.zip"
          if (Test-Path $dst) { Remove-Item $dst -Force }
          Compress-Archive -Path $src -DestinationPath $dst -CompressionLevel Optimal
          
      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: video-trimmer-windows
          path: dist/video-trimmer-*-windows.zip
          retention-days: 30

  build-macos:
    name: Build for macOS
    runs-on: macos-latest
    env:
      APP_VERSION: ${{ github.ref_name }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          
      - name: Install dependencies
        run: |
          echo "Attempting to install dependencies with npm ci..."
          npm ci || {
            echo "npm ci failed, trying npm install instead..."
            npm install
          }
        
      - name: Download external dependencies
        run: node scripts/download-deps.js
        
      - name: Build application
        run: npm run build
        
      - name: Package application
        run: npx tsx scripts/build-electron.ts
        
      - name: Create macOS archive
        run: |
          cd dist
          for dir in video-trimmer-*-darwin-*; do
            tar -czf "${dir}.tar.gz" "$dir"
          done
          
      - name: Upload macOS artifacts
        uses: actions/upload-artifact@v4
        with:
          name: video-trimmer-macos
          path: dist/*.tar.gz
          retention-days: 30

  build-linux:
    name: Build for Linux
    runs-on: ubuntu-latest
    env:
      APP_VERSION: ${{ github.ref_name }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip curl tar xz-utils ffmpeg
          
      - name: Install dependencies
        run: |
          echo "Attempting to install dependencies with npm ci..."
          npm ci || {
            echo "npm ci failed, trying npm install instead..."
            npm install
          }
        
      - name: Download external dependencies
        run: node scripts/download-deps.js
        
      - name: Build application
        run: npm run build
        
      - name: Package application
        run: npx tsx scripts/build-electron.ts
        
      - name: Create Linux archive
        run: |
          cd dist
          for dir in video-trimmer-*-linux-*; do
            tar -czf "${dir}.tar.gz" "$dir"
          done
          
      - name: Upload Linux artifacts
        uses: actions/upload-artifact@v4
        with:
          name: video-trimmer-linux
          path: dist/*.tar.gz
          retention-days: 30

  create-release:
    name: Create Release
    needs: [build-windows, build-macos, build-linux]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          
      - name: Create Release (Linux/macOS assets)
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/video-trimmer-macos/*.tar.gz
            artifacts/video-trimmer-linux/*.tar.gz
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Windows asset
        uses: svenstaro/upload-release-action@v2
        with:
          file: artifacts/video-trimmer-windows/video-trimmer-${{ github.ref_name }}-windows.zip
          asset_name: video-trimmer-${{ github.ref_name }}-windows.zip
          tag: ${{ github.ref_name }}
          overwrite: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
